# Εισάγοντας τη βιβλιοθήκη Pandas

In [1]:
import pandas as pd
import numpy as np

## 1.2 Δημιουργία και χρήση των σειρών Pandas

In [3]:
labels = ['first', 'second', 'third']
values = [10, 20, 30]
array = np.arange(10,31,10)
dico = {'first':10,'second':20,'third':30}

In [4]:
#lista arithmon
A = pd.Series(values)
A

0    10
1    20
2    30
dtype: int64

In [6]:
#lista arithmon kai strings
B = pd.Series(values,labels)
B

first     10
second    20
third     30
dtype: int64

In [9]:
# array kai labels
C = pd.Series(array,labels)
C

first     10
second    20
third     30
dtype: int64

In [10]:
#lexiko
D = pd.Series(dico)
D

first     10
second    20
third     30
dtype: int64

# Ευρετηρίαση σειρών με χρήση ετικετών

In [15]:
A = pd.Series([1,2,3,4],['Smart','Opel','Audi','Porsche'])
A

Smart      1
Opel       2
Audi       3
Porsche    4
dtype: int64

In [16]:
A['Smart']

np.int64(1)

In [17]:
A = pd.Series(['Smart','Opel','Audi','Porsche'],[1,2,3,4])
A

1      Smart
2       Opel
3       Audi
4    Porsche
dtype: object

In [18]:
A[1]

'Smart'

## 2.1 Πρόσθεση σειρών

In [20]:
A = pd.Series([1,2,3,4],['Smart','Opel','Audi','Porsche'])
A
doubleA=A+A
doubleA

Smart      2
Opel       4
Audi       6
Porsche    8
dtype: int64

#  ΠΛΑΙΣΙΑ ΔΕΔΟΜΕΝΩΝ (DATA FRAMES)

In [21]:
s1 = pd.Series([1,2,3,4],['Smart','Opel','Audi','Porsche'])
df1 = pd.DataFrame([s1])
df1

   Smart  Opel  Audi  Porsche
0      1     2     3        4

In [23]:
s2 = pd.Series([10,20,30,40],['Smart','Opel','Audi','Porsche'])
index = 'Row1 Row2'.split()
df2 = pd.DataFrame([s1,s2],index)
df2

      Smart  Opel  Audi  Porsche
Row1      1     2     3        4
Row2     10    20    30       40

## 3.2 Παίρνοντας δεδομένα από ένα πλαίσιο δεδομένων

In [24]:
array = np.arange(1,21).reshape(5,4)
row = 'Row1 Row2 Row3 Row4 Row5'.split()
col = 'Col1 Col2 Col3 Col4'.split()
df3 = pd.DataFrame(array,row,col)
df3

      Col1  Col2  Col3  Col4
Row1     1     2     3     4
Row2     5     6     7     8
Row3     9    10    11    12
Row4    13    14    15    16
Row5    17    18    19    20

In [25]:
df3['Col1']

Row1     1
Row2     5
Row3     9
Row4    13
Row5    17
Name: Col1, dtype: int64

In [27]:
df3[['Col1','Col2']]

      Col1  Col2
Row1     1     2
Row2     5     6
Row3     9    10
Row4    13    14
Row5    17    18

In [29]:
df3['Col2']['Row5']

np.int64(18)

In [31]:
df3.loc['Row1']

Col1    1
Col2    2
Col3    3
Col4    4
Name: Row1, dtype: int64

## 3.3 Εισαγωγή, διαγραφή και πρόσθεση στηλών

In [32]:
df3['Col sum'] = df3['Col1'] + df3['Col2']
df3

      Col1  Col2  Col3  Col4  Col sum
Row1     1     2     3     4        3
Row2     5     6     7     8       11
Row3     9    10    11    12       19
Row4    13    14    15    16       27
Row5    17    18    19    20       35

In [34]:
df3['zeros'] = np.zeros(5)
df3

      Col1  Col2  Col3  Col4  Col sum  zeros
Row1     1     2     3     4        3    0.0
Row2     5     6     7     8       11    0.0
Row3     9    10    11    12       19    0.0
Row4    13    14    15    16       27    0.0
Row5    17    18    19    20       35    0.0

In [35]:
df3.drop('zeros',axis=1,inplace=True)
df3

      Col1  Col2  Col3  Col4  Col sum
Row1     1     2     3     4        3
Row2     5     6     7     8       11
Row3     9    10    11    12       19
Row4    13    14    15    16       27
Row5    17    18    19    20       35

# 4. Πρακτικό παράδειγμα

In [38]:
df3[df3>8]

      Col1  Col2  Col3  Col4  Col sum
Row1   NaN   NaN   NaN   NaN      NaN
Row2   NaN   NaN   NaN   NaN     11.0
Row3   9.0  10.0  11.0  12.0     19.0
Row4  13.0  14.0  15.0  16.0     27.0
Row5  17.0  18.0  19.0  20.0     35.0

In [39]:
df3[df3!=8]

      Col1  Col2  Col3  Col4  Col sum
Row1     1     2     3   4.0        3
Row2     5     6     7   NaN       11
Row3     9    10    11  12.0       19
Row4    13    14    15  16.0       27
Row5    17    18    19  20.0       35

In [40]:
#afairesi seiras 3
df3[df3['Col1']!=9]

      Col1  Col2  Col3  Col4  Col sum
Row1     1     2     3     4        3
Row2     5     6     7     8       11
Row4    13    14    15    16       27
Row5    17    18    19    20       35

# 5. ΕΛΛΕΙΠΟΝΤΑ ΣΤΟΙΧΕΙΑ (MISSING DATA)

In [42]:
dico = {'x':[1,2,np.nan],'y':[4,np.nan,np.nan],'z':[7,8,9]}
dico

{'x': [1, 2, nan], 'y': [4, nan, nan], 'z': [7, 8, 9]}

In [52]:
row = 'A B C'.split()
df = pd.DataFrame(dico,row)
df

     x    y  z
A  1.0  4.0  7
B  2.0  NaN  8
C  NaN  NaN  9

In [44]:
df.dropna()

     x    y  z
A  1.0  4.0  7

In [46]:
df.dropna(axis=1)

   z
A  7
B  8
C  9

In [49]:
df.dropna(thresh=2)

     x    y  z
A  1.0  4.0  7
B  2.0  NaN  8

In [51]:
df.fillna('X')

     x    y  z
A  1.0  4.0  7
B  2.0    X  8
C    X    X  9

In [53]:
df['x'].fillna(value=df['x'].mean())

A    1.0
B    2.0
C    1.5
Name: x, dtype: float64

# 6. ΕΙΣΑΓΩΓΗ ΑΡΧΕΙΟΥ CSV ΚΑΙ ΑΝΑΓΝΩΣΗ ΔΕΔΟΜΕΝΩΝ

In [54]:
pwd()

'C:\\Users\\user'

In [55]:
data = pd.read_csv('data.csv')
data

   col1  col2  col3  col4
0     1     2     3     4
1     5     6     7     8
2     9    10    11    12
3    13    14    15    16

# 7. DATA MUNGING - ΚΑΘΑΡΙΣΜΟΣ ΚΑΙ ΜΕΤΑΣΧΗΜΑΤΙΣΜΟΣ ΔΕΔΟΜΕΝΩΝ

In [62]:
from urllib.request import urlretrieve

In [63]:
iris = 'http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [64]:
urlretrieve(iris)

('C:\\Users\\user\\AppData\\Local\\Temp\\tmpqbk3c41w',
 <http.client.HTTPMessage at 0x27837128410>)

In [65]:
df = pd.read_csv(iris, sep=',')
df

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [66]:
col_names = ['sepallen', 'sepalwid', 'petallen', 'petalwid', 'class']
df.columns = col_names

In [67]:
df

     sepallen  sepalwid  petallen  petalwid           class
0         4.9       3.0       1.4       0.2     Iris-setosa
1         4.7       3.2       1.3       0.2     Iris-setosa
2         4.6       3.1       1.5       0.2     Iris-setosa
3         5.0       3.6       1.4       0.2     Iris-setosa
4         5.4       3.9       1.7       0.4     Iris-setosa
..        ...       ...       ...       ...             ...
144       6.7       3.0       5.2       2.3  Iris-virginica
145       6.3       2.5       5.0       1.9  Iris-virginica
146       6.5       3.0       5.2       2.0  Iris-virginica
147       6.2       3.4       5.4       2.3  Iris-virginica
148       5.9       3.0       5.1       1.8  Iris-virginica

[149 rows x 5 columns]

In [68]:
df.head()

   sepallen  sepalwid  petallen  petalwid        class
0       4.9       3.0       1.4       0.2  Iris-setosa
1       4.7       3.2       1.3       0.2  Iris-setosa
2       4.6       3.1       1.5       0.2  Iris-setosa
3       5.0       3.6       1.4       0.2  Iris-setosa
4       5.4       3.9       1.7       0.4  Iris-setosa

In [69]:
df.head(2)

   sepallen  sepalwid  petallen  petalwid        class
0       4.9       3.0       1.4       0.2  Iris-setosa
1       4.7       3.2       1.3       0.2  Iris-setosa

In [70]:
df.columns

Index(['sepallen', 'sepalwid', 'petallen', 'petalwid', 'class'], dtype='object')

In [71]:
col_class = df['class']
col_class

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
144    Iris-virginica
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
Name: class, Length: 149, dtype: object

In [72]:
mask = df['sepallen'] > 6.0
mask

0      False
1      False
2      False
3      False
4      False
       ...
144     True
145     True
146     True
147     True
148    False
Name: sepallen, Length: 149, dtype: bool

In [74]:
maskc =df['class'] == 'Iris-virginica'
df.loc[maskc, 'class'] = 'new label'
df

     sepallen  sepalwid  petallen  petalwid        class
0         4.9       3.0       1.4       0.2  Iris-setosa
1         4.7       3.2       1.3       0.2  Iris-setosa
2         4.6       3.1       1.5       0.2  Iris-setosa
3         5.0       3.6       1.4       0.2  Iris-setosa
4         5.4       3.9       1.7       0.4  Iris-setosa
..        ...       ...       ...       ...          ...
144       6.7       3.0       5.2       2.3    new label
145       6.3       2.5       5.0       1.9    new label
146       6.5       3.0       5.2       2.0    new label
147       6.2       3.4       5.4       2.3    new label
148       5.9       3.0       5.1       1.8    new label

[149 rows x 5 columns]

In [75]:
df['class'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'new label'], dtype=object)

In [76]:
groupcm = df.groupby('class').mean()
groupcm

                 sepallen  sepalwid  petallen  petalwid
class
Iris-setosa      5.004082  3.416327  1.465306  0.244898
Iris-versicolor  5.936000  2.770000  4.260000  1.326000
new label        6.588000  2.974000  5.552000  2.026000

In [77]:
# Askisi

In [79]:
iris = 'http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
urlretrieve(iris)

('C:\\Users\\user\\AppData\\Local\\Temp\\tmpr0iqq0wn',
 <http.client.HTTPMessage at 0x27837e4d5b0>)

In [80]:
df  = pd.read_csv(iris, sep=',')
df

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [81]:
cols = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
df.columns = cols
df

     sepal_length  sepal_width  petal_length  petal_width           class
0             4.9          3.0           1.4          0.2     Iris-setosa
1             4.7          3.2           1.3          0.2     Iris-setosa
2             4.6          3.1           1.5          0.2     Iris-setosa
3             5.0          3.6           1.4          0.2     Iris-setosa
4             5.4          3.9           1.7          0.4     Iris-setosa
..            ...          ...           ...          ...             ...
144           6.7          3.0           5.2          2.3  Iris-virginica
145           6.3          2.5           5.0          1.9  Iris-virginica
146           6.5          3.0           5.2          2.0  Iris-virginica
147           6.2          3.4           5.4          2.3  Iris-virginica
148           5.9          3.0           5.1          1.8  Iris-virginica

[149 rows x 5 columns]

In [82]:
mask =df['class'] == 'Iris-virginica'
df.loc[maskc, 'class'] = 'new label'
df

     sepal_length  sepal_width  petal_length  petal_width        class
0             4.9          3.0           1.4          0.2  Iris-setosa
1             4.7          3.2           1.3          0.2  Iris-setosa
2             4.6          3.1           1.5          0.2  Iris-setosa
3             5.0          3.6           1.4          0.2  Iris-setosa
4             5.4          3.9           1.7          0.4  Iris-setosa
..            ...          ...           ...          ...          ...
144           6.7          3.0           5.2          2.3    new label
145           6.3          2.5           5.0          1.9    new label
146           6.5          3.0           5.2          2.0    new label
147           6.2          3.4           5.4          2.3    new label
148           5.9          3.0           5.1          1.8    new label

[149 rows x 5 columns]

In [83]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width        class
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa
2           4.6          3.1           1.5          0.2  Iris-setosa
3           5.0          3.6           1.4          0.2  Iris-setosa
4           5.4          3.9           1.7          0.4  Iris-setosa

In [84]:
grouped = df.groupby('class').sum()
grouped

                 sepal_length  sepal_width  petal_length  petal_width
class
Iris-setosa             245.2        167.4          71.8         12.0
Iris-versicolor         296.8        138.5         213.0         66.3
new label               329.4        148.7         277.6        101.3